"""initial_schema

Revision ID: 8ef269c4d8ed
Revises: 
Create Date: 2026-09-19 21:20:43.597523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ef269c4d8ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcast_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('center', sa.String(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('recipients_count', sa.Integer(), nullable=True),
    sa.Column('sent_by', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcast_log_id'), 'broadcast_log', ['id'], unique=False)
    op.create_index(op.f('ix_broadcast_log_sent_at'), 'broadcast_log', ['sent_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('hazard_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hazard_type', sa.String(length=30), nullable=False),
    sa.Column('geom', sa.Text(), nullable=True),
    sa.Column('geom_geojson', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hazard_zones_id'), 'hazard_zones', ['id'], unique=False)
    op.create_table('news_flash',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_flash_id'), 'news_flash', ['id'], unique=False)
    op.create_index(op.f('ix_news_flash_published_at'), 'news_flash', ['published_at'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hazard_type', sa.String(length=30), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('mesh_level', sa.Integer(), nullable=True),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('is_gateway', sa.Boolean(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_code'), 'nodes', ['code'], unique=True)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('whatsapp_number', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribers_id'), 'subscribers', ['id'], unique=False)
    op.create_index(op.f('ix_subscribers_whatsapp_number'), 'subscribers', ['whatsapp_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('weather_forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('forecast_time', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('predicted_at', sa.DateTime(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_forecasts_forecast_time'), 'weather_forecasts', ['forecast_time'], unique=False)
    op.create_index(op.f('ix_weather_forecasts_id'), 'weather_forecasts', ['id'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.Column('wind_kmh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_ts'), 'weather_observations', ['ts'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('hazard_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('decided_on_device', sa.Boolean(), nullable=True),
    sa.Column('decision_ms', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('node_timestamp', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_after_outage', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ground_truth', sa.String(length=20), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_node_id'), 'alerts', ['node_id'], unique=False)
    op.create_table('mesh_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_node_id', sa.Integer(), nullable=False),
    sa.Column('to_node_id', sa.Integer(), nullable=False),
    sa.Column('rssi', sa.Float(), nullable=True),
    sa.Column('link_type', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_node_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesh_links_id'), 'mesh_links', ['id'], unique=False)
    op.create_table('readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('water_level_cm', sa.Float(), nullable=True),
    sa.Column('water_rate_cm_min', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_dir', sa.Float(), nullable=True),
    sa.Column('smoke_index', sa.Float(), nullable=True),
    sa.Column('raw_bytes', sa.Integer(), nullable=True),
    sa.Column('tx_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_index(op.f('ix_readings_node_id'), 'readings', ['node_id'], unique=False)
    op.create_index(op.f('ix_readings_ts'), 'readings', ['ts'], unique=False)
    op.create_table('whatsapp_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('parsed_intent', sa.String(length=50), nullable=True),
    sa.Column('verdict', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_messages_id'), 'whatsapp_messages', ['id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_ts'), 'whatsapp_messages', ['ts'], unique=False)
    op.drop_index(op.f('ix_incident_alerts_id'), table_name='incident_alerts')
    op.drop_table('incident_alerts')
    op.drop_index(op.f('ix_telemetry_records_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_node_id'), table_name='telemetry_records')
    op.drop_index(op.f('ix_telemetry_records_timestamp'), table_name='telemetry_records')
    op.drop_table('telemetry_records')
    op.drop_index(op.f('ix_sensor_nodes_id'), table_name='sensor_nodes')
    op.drop_table('sensor_nodes')
    op.drop_index(op.f('ix_safe_shelters_id'), table_name='safe_shelters')
    op.drop_table('safe_shelters')
    op.drop_index(op.f('ix_whatsapp_verifications_id'), table_name='whatsapp_verifications')
    op.drop_index(op.f('ix_whatsapp_verifications_incident_id'), table_name='whatsapp_verifications')
    op.drop_table('whatsapp_verifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_verifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('incident_id', sa.INTEGER(), nullable=True),
    sa.Column('sarpanch_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=30), nullable=False),
    sa.Column('query_sent', sa.TEXT(), nullable=False),
    sa.Column('query_language', sa.VARCHAR(length=10), nullable=True),
    sa.Column('response_received', sa.TEXT(), nullable=True),
    sa.Column('verification_status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('nlp_confidence', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_verifications_incident_id'), 'whatsapp_verifications', ['incident_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_verifications_id'), 'whatsapp_verifications', ['id'], unique=False)
    op.create_table('safe_shelters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), nullable=False),
    sa.Column('shelter_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('capacity', sa.INTEGER(), nullable=True),
    sa.Column('current_occupancy', sa.INTEGER(), nullable=True),
    sa.Column('contact_number', sa.VARCHAR(length=30), nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safe_shelters_id'), 'safe_shelters', ['id'], unique=False)
    op.create_table('sensor_nodes',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('hazard_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('parent_node_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hop_count', sa.INTEGER(), nullable=True),
    sa.Column('battery_pct', sa.FLOAT(), nullable=True),
    sa.Column('signal_rssi', sa.FLOAT(), nullable=True),
    sa.Column('is_gateway', sa.BOOLEAN(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_nodes_id'), 'sensor_nodes', ['id'], unique=False)
    op.create_table('telemetry_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('node_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('water_level_m', sa.FLOAT(), nullable=True),
    sa.Column('water_rate_of_change', sa.FLOAT(), nullable=True),
    sa.Column('temperature_c', sa.FLOAT(), nullable=True),
    sa.Column('humidity_pct', sa.FLOAT(), nullable=True),
    sa.Column('wind_speed_kmh', sa.FLOAT(), nullable=True),
    sa.Column('wind_direction_deg', sa.FLOAT(), nullable=True),
    sa.Column('pm25', sa.FLOAT(), nullable=True),
    sa.Column('pm10', sa.FLOAT(), nullable=True),
    sa.Column('mesh_hops', sa.INTEGER(), nullable=True),
    sa.Column('raw_payload', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['sensor_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_records_timestamp'), 'telemetry_records', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_records_node_id'), 'telemetry_records', ['node_id'], unique=False)
    op.create_index(op.f('ix_telemetry_records_id'), 'telemetry_records', ['id'], unique=False)
    op.create_table('incident_alerts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hazard_type', sa.VARCHAR(length=30), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=30), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('radius_km', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('verified_by_human', sa.BOOLEAN(), nullable=True),
    sa.Column('verification_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('evacuation_triggered', sa.BOOLEAN(), nullable=True),
    sa.Column('ndrf_dispatched', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_alerts_id'), 'incident_alerts', ['id'], unique=False)
    op.drop_index(op.f('ix_whatsapp_messages_ts'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_id'), table_name='whatsapp_messages')
    op.drop_table('whatsapp_messages')
    op.drop_index(op.f('ix_readings_ts'), table_name='readings')
    op.drop_index(op.f('ix_readings_node_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_table('readings')
    op.drop_index(op.f('ix_mesh_links_id'), table_name='mesh_links')
    op.drop_table('mesh_links')
    op.drop_index(op.f('ix_alerts_node_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_weather_observations_ts'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_weather_forecasts_id'), table_name='weather_forecasts')
    op.drop_index(op.f('ix_weather_forecasts_forecast_time'), table_name='weather_forecasts')
    op.drop_table('weather_forecasts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscribers_whatsapp_number'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_id'), table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_code'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_news_flash_published_at'), table_name='news_flash')
    op.drop_index(op.f('ix_news_flash_id'), table_name='news_flash')
    op.drop_table('news_flash')
    op.drop_index(op.f('ix_hazard_zones_id'), table_name='hazard_zones')
    op.drop_table('hazard_zones')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_broadcast_log_sent_at'), table_name='broadcast_log')
    op.drop_index(op.f('ix_broadcast_log_id'), table_name='broadcast_log')
    op.drop_table('broadcast_log')
    # ### end Alembic commands ###
